plot(app.SavingsPlot,Time,Savings/1e6,'k')
hold(app.SavingsPlot,'on') 
grid(app.SavingsPlot,'on')
plot(app.SavingsPlot,Time,IncomePensionMoney/1e6,'c')
plot(app.SavingsPlot,Time,PremiePensionMoney/1e6,'b')
plot(app.SavingsPlot,Time,ServicePensionMoney/1e6,'g')
plot(app.SavingsPlot,Time,TaxableSavings/1e6,'r')
hold(app.SavingsPlot, 'off')
legend(app.SavingsPlot,"Savings","Income Pen","Premie Pen","Service Pen", "Taxable Savings")
ylabel(app.SavingsPlot,'Capital, [Mkr]')
xlabel(app.SavingsPlot,'Age, [Years]')
ylim(app.SavingsPlot,[0,min(max(Expenses)*1.3/(ROI-1)/1e6+1,8)]) %Y axis only goes up to the amount of Savings that can sustain the maximum expenses according to the ROI+1msek
xlim(app.SavingsPlot,[CurrentAge,IWillLiveTo])
%%
plot(app.EarningsPlot,Time,TotalPensionPayout/1e3,'m')
hold(app.EarningsPlot,'on') 
grid(app.EarningsPlot,"on")
plot(app.EarningsPlot,Time,IncomePensionPayout/1e3,'g')
plot(app.EarningsPlot,Time,PremiePensionPayout/1e3,'c')
plot(app.EarningsPlot,Time,ServicePensionPayout/1e3,'b')
plot(app.EarningsPlot,Time,Income/1e3,'k')
plot(app.EarningsPlot,Time,IncomeFromROI/1e3,'k:')
plot(app.EarningsPlot,Time,PremieFromROI/1e3,'c:')
plot(app.EarningsPlot,Time,ServiceFromROI/1e3,'b:')
hold(app.EarningsPlot,"off")
legend(app.EarningsPlot,"Total Pension Payout","Income Pen","Premie Pen","Service Pen","Income","ROI Savings","ROI Premie","ROI Service")
ylabel(app.EarningsPlot,'Amount [Tkr]')
xlabel(app.EarningsPlot,'Age, [Years]')
ylim(app.EarningsPlot,[0,max(max(Income),max(TotalPensionPayout))/1e3+5])
xlim(app.EarningsPlot,[CurrentAge,IWillLiveTo])